[project]
name = "cod8a"
version = "0.1.0"
description = "cod8a is a code documentation and visualization tool for Python and .NET projects"
authors = [
    { name = "Akumbom",email = "akumbom5ma@gmail.com"}
]
maintainers = [ 
    { name = "Marietta Akumbom" }
 ]
keywords = [ "visualization", "uml", "docs", "flowchart", "class", "sequence", "diagram" ]
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click (>=8.3.3,<9.0.0)",
    "pydantic (>=2.13.3,<3.0.0)"
]

[tool.poetry]
packages = [{include = "cod8a", from = "src"}]
include = [
    { path = "src/cod8a/dotnet/CodeAnalyzer/bin/Release/net10.0/*.dll", format = ["wheel"] },
    { path = "src/cod8a/dotnet/CodeAnalyzer/bin/Release/net10.0/*.json", format = ["wheel"] }
]

[tool.poetry.scripts]
cod8a = "cod8a.cli:main"
cde8a = "cod8a.cli:doc_main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.3,<10.0.0)"
]
