graph TD
    file_1["File: models.py"]
    file_1 --> cls_9["Class: UsingDirective"]
    file_1 --> cls_14["Class: ParameterStructure"]
    file_1 --> cls_20["Class: FieldStructure"]
    file_1 --> cls_27["Class: MethodStructure"]
    file_1 --> cls_31["Class: Relationship"]
    file_1 --> cls_39["Class: ClassStructure"]
    file_1 --> cls_45["Class: FileStructure"]
    file_1 --> cls_49["Class: ProjectStructure"]