graph TD
    file_1["File: models.py"]
    file_1 --> cls_9["Class: UsingDirective"]
    cls_9 --> f_7["id (int)"]
    cls_9 --> f_8["name (str)"]
    file_1 --> cls_14["Class: ParameterStructure"]
    cls_14 --> f_10["name (str)"]
    cls_14 --> f_11["modifier (str)"]
    cls_14 --> f_12["type (str)"]
    cls_14 --> f_13["summary (str)"]
    file_1 --> cls_20["Class: FieldStructure"]
    cls_20 --> f_15["id (int)"]
    cls_20 --> f_16["name (str)"]
    cls_20 --> f_17["modifier (str)"]
    cls_20 --> f_18["type (str)"]
    cls_20 --> f_19["summary (str)"]
    file_1 --> cls_27["Class: MethodStructure"]
    cls_27 --> f_21["id (int)"]
    cls_27 --> f_22["name (str)"]
    cls_27 --> f_23["modifier (str)"]
    cls_27 --> f_24["return_type (str)"]
    cls_27 --> f_25["parameters (List[ParameterStructure])"]
    cls_27 --> f_26["summary (str)"]
    file_1 --> cls_31["Class: Relationship"]
    cls_31 --> f_28["id (int)"]
    cls_31 --> f_29["type (str)"]
    cls_31 --> f_30["parent_name (str)"]
    file_1 --> cls_39["Class: ClassStructure"]
    cls_39 --> f_32["id (int)"]
    cls_39 --> f_33["name (str)"]
    cls_39 --> f_34["methods (List[MethodStructure])"]
    cls_39 --> f_35["fields (List[FieldStructure])"]
    cls_39 --> f_36["type (str)"]
    cls_39 --> f_37["associated_item (List[Relationship])"]
    cls_39 --> f_38["summary (str)"]
    file_1 --> cls_45["Class: FileStructure"]
    cls_45 --> f_41["id (int)"]
    cls_45 --> f_42["name (str)"]
    cls_45 --> f_43["using_directives (Optional[List[UsingDirective]])"]
    cls_45 --> f_44["classes (Optional[List[ClassStructure]])"]
    file_1 --> cls_49["Class: ProjectStructure"]
    cls_49 --> f_47["name (str)"]
    cls_49 --> f_48["files (List[FileStructure])"]