classDiagram
    class FileParser {
        +string Name
        +string FilePath
        +Parse() T
        -GetName(NameSyntax? nameSyntax) string
        -GetClassDeclaration(CompilationUnitSyntax root) List<ClassStructure>
    }

    BaseParser <|-- FileParser : inherits