## TODO 

# name: Publish to PyPI

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'pyproject.toml'

# jobs:
#   check-version:
#     name: Check for version change
#     runs-on: ubuntu-latest
#     outputs:
#       changed: ${{ steps.version-check.outputs.changed }}
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 2 # Fetch previous commit to compare
#       - name: Detect version change
#         id: version-check
#         run: |
#           NEW_VERSION=$(grep -m 1 "^version = " pyproject.toml | cut -d'"' -f2)
#           OLD_VERSION=$(git show HEAD^:pyproject.toml | grep -m 1 "^version = " | cut -d'"' -f2 || echo "none")
          
#           echo "Old version: $OLD_VERSION"
#           echo "New version: $NEW_VERSION"
          
#           if [ "$NEW_VERSION" != "$OLD_VERSION" ]; then
#             echo "Version changed detected."
#             echo "changed=true" >> $GITHUB_OUTPUT
#           else
#             echo "No version change detected."
#             echo "changed=false" >> $GITHUB_OUTPUT
#           fi

#   build:
#     name: Build distribution
#     needs: check-version
#     if: needs.check-version.outputs.changed == 'true'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.13"
#       - name: Install Poetry
#         run: pip install poetry
#       - name: Build package
#         run: poetry build
#       - name: Store distribution packages
#         uses: actions/upload-artifact@v4
#         with:
#           name: python-package-distributions
#           path: dist/

#   publish-to-testpypi:
#     name: Publish to TestPyPI
#     needs: [check-version, build]
#     if: needs.check-version.outputs.changed == 'true'
#     runs-on: ubuntu-latest
#     environment:
#       name: test
#     permissions:
#       id-token: write
#     steps:
#       - name: Download distribution packages
#         uses: actions/download-artifact@v4
#         with:
#           name: python-package-distributions
#           path: dist/
#       - name: Publish to TestPyPI
#         uses: pypa/gh-action-pypi-publish@release/v1
#         with:
#           repository-url: https://test.pypi.org/legacy/
#           password: ${{ secrets.PYPI_TEST_TOKEN }}

#   publish-to-pypi:
#     name: Publish to PyPI
#     needs: [check-version, publish-to-testpypi]
#     if: needs.check-version.outputs.changed == 'true'
#     runs-on: ubuntu-latest
#     environment:
#       name: production
#     permissions:
#       id-token: write
#     steps:
#       - name: Download distribution packages
#         uses: actions/download-artifact@v4
#         with:
#           name: python-package-distributions
#           path: dist/
#       - name: Publish to PyPI
#         uses: pypa/gh-action-pypi-publish@release/v1
#         with:
#           password: ${{ secrets.PYPI_TOKEN }}
